# Generated by Django 5.0.3 on 2024-03-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_album',
            new_name='artist',
        ),
    ]
