GENRES = (
    (1, "Pop"),
    (2, "Rock"),
    (3, "Hip-Hop & Rap"),
    (4, "Country"),
    (5, "R&b"),
    (6, "Folk"),
    (7, "Jazz"),
    (8, "Heavy Metal"),
    (9, "EDM"),
    (10, "Soul"),
    (11, "Funk"),
    (12, "Reggae"),
    (13, "Disco"),
    (14, "Punk Rock"),
    (15, "Classical"),
    (16, "House"),
    (17, "Techno"),
    (18, "Indie Rock"),
    (19, "Grunge"),
    (20, "Ambient"),
    (21, "Gospel"),
    (22, "Latin Music"),
    (23, "Grime"),
    (24, "Trap"),
    (25, "Psychedelic Rock"),
)
