GENRES = (
    ("Pop", "Pop"),
    ("Rock", "Rock"),
    ("Hip-Hop & Rap", "Hip-Hop & Rap"),
    ("Country", "Country"),
    ("R&b", "R&b"),
    ("Folk", "Folk"),
    ("Jazz", "Jazz"),
    ("Heavy Metal", "Heavy Metal"),
    ("Edm", "EDM"),
    ("Soul", "Soul"),
    ("Funk", "Funk"),
    ("Reggae", "Reggae"),
    ("Disco", "Disco"),
    ("Punk Rock", "Punk Rock"),
    ("Classical", "Classical"),
    ("House", "House"),
    ("Techno", "Techno"),
    ("Indie Rock", "Indie Rock"),
    ("Grunge", "Grunge"),
    ("Ambient", "Ambient"),
    ("Gospel", "Gospel"),
    ("Latin Music", "Latin Music"),
    ("Grime", "Grime"),
    ("Trap", "Trap"),
    ("Psychedelic Rock", "Psychedelic Rock"),
)
