# Generated by Django 5.0.3 on 2024-03-28 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
