# Generated by Django 5.0.3 on 2024-03-20 20:34

import apps.utils.helpers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True, max_length=2000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='artists.artist')),
            ],
            options={
                'verbose_name_plural': 'Songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=apps.utils.helpers.get_genres, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(related_name='songs_genre', to='songs.song')),
            ],
            options={
                'verbose_name_plural': "Song Genre's",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongMedia',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='song_media')),
                ('file', models.FileField(upload_to='music_folder')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_media', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_media', to='artists.artist')),
            ],
            options={
                'verbose_name_plural': "Song's Media",
                'ordering': ['-created_at'],
            },
        ),
    ]
