# Generated by Django 5.0.3 on 2024-03-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songmedia',
            old_name='song_media',
            new_name='artist',
        ),
    ]
