# Generated by Django 5.0.3 on 2024-03-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_song_media_songmedia_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songgenre',
            old_name='category_id',
            new_name='genre_id',
        ),
        migrations.RemoveField(
            model_name='songgenre',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='songmedia',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_genre', to='songs.songgenre'),
        ),
        migrations.AddField(
            model_name='songmedia',
            name='song',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_media', to='songs.song'),
            preserve_default=False,
        ),
    ]
