# Generated by Django 5.0.3 on 2024-03-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_category_id_songgenre_genre_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='id',
            new_name='song_id',
        ),
    ]
