# Generated by Django 5.0.3 on 2024-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rename_id_song_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
