# Generated by Django 5.0.3 on 2024-03-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
